### ISSUE TITLE
FTP Support

### ISSUE THREAD

**Issue by iSaluki** [Neocky/pluGET#15]
Lots of Minecraft hosting companies only provide FTP support, so it is not possible to use pluGET with them. Adding FTP support would increase the number of supported services massively.

**Comment by Neocky** [comment]
Thank you for your suggestion.
FTP Support is definetly possible but i know only of hosting providers which use the secure FTP protocol which is SFTP. 
Can you give me an example of a hosting provider which still uses the unsecure FTP protocol?

**Comment by iSaluki** [comment]
PebbleHost only supports FTP as far as I am aware

**Comment by Neocky** [comment]
I checked and you are right!
I will add FTP support in the next updates when i got time.

**Comment by Neocky** [comment]
FTP Support added in Version: [1.5.0](https://github.com/Neocky/pluGET/releases/tag/v1.5.0)
Update to the latest version and you are good to go!
