### ISSUE TITLE
CurseForge support

### ISSUE THREAD

**Issue by Freddo3000** [Neocky/pluGET#21]
**Is your feature request related to a problem? Please describe.**
In addition to being able to download from Spigot, it would be useful to be able to download plugins from CurseForge as well.

**Describe the solution you'd like**
Curseforge support

**Comment by Freddo3000** [comment]
Ticket can probably be merged into https://github.com/Neocky/pluGET/issues/13 actually. Not sure if there is any difference between https://dev.bukkit.org/bukkit-plugins and https://www.curseforge.com/minecraft/bukkit-plugins

**Comment by Neocky** [comment]
Merged into #13
