### ISSUE TITLE
Shows N/A on some plugins for latest V and Update

### ISSUE THREAD

**Issue by PyricDemon** [Neocky/pluGET#24]
**Describe the bug**
The pluGET program shows N/A for some plugins like Citizens, Essentials, HolographicDisplays, Luckperms and many more in my collection of plugins. It would show the N/A only In the latest V. and Update available

**To Reproduce**
1. Go to 'launcher.bat'
2. Open on 'launcher.bat'
3. Type in 'Check all'
4. Have X, Y and Z plugins installed
5. See Error

**Expected behavior**
Show me all current, available, and possible versions I can be using

**Screenshots**
![image_2021-05-28_172416](https://user-images.githubusercontent.com/79799834/120043198-87146000-bfd9-11eb-8bc0-63234bbdf08d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit

**Additional context**

**Comment by Neocky** [comment]
Hey @PyricDemon,

some of your plugins are from bukkit, like worldedit, which pluGET doesn't support currently. 
Then some are premium plugins which won't work and the rest has inconsisten name and version namings.  
Sadly only the plugin authors can fix the issues but there exists a way to make for example EssentialsX work.  
Check the documentation [here](https://github.com/Neocky/pluGET#inconsistent-names-and-versions) to make the plugins work.  

### Nontheless thank you for flying with pluGET 🚀

**Comment by GreenDiscord** [comment]
Any chance you can let a user set a username for a certian plugin, for a temp fix
