### ISSUE TITLE
No results when using SFTP

### ISSUE THREAD

**Issue by mmuziek** [Neocky/pluGET#26]
**Describe the bug**
When using check all no plugins are shown same for specific checks.

**To Reproduce**
1. Go to install and setup SFTP
2. Check in filezilla if the SFTP is working and check the path.
3. enter them all in Pluget.
4. start pluget and check all
5. Nothing pops up just a 0 of 0 result

**Expected behavior**
i expect a list of plugins i have together with their version and if a update is there.

**Screenshots**
https://prnt.sc/13l73x7

**Desktop (please complete the following information):**
 - OS Windows 10

**Additional context**
the only error is the hosts file error Like u already know off

**Comment by Neocky** [comment]
Hey @mmuziek, 
i am aware of the issue and will fix it when i've got time!
For the time being revert to the version [1.5.5](https://github.com/Neocky/pluGET/releases/tag/1.5.5)
It should work with that!

**Comment by Neocky** [comment]
Hey @mmuziek,
i updated pluGET with a fix for your problem!
Update to the latest version and you are good to go: [v1.5.7](https://github.com/Neocky/pluGET/releases/tag/1.5.7)

### Thank you for flying with pluGET 🚀
