### ISSUE TITLE
"check" command fails when "separate download path" is set

### ISSUE THREAD

**Issue by smcclennon** [Neocky/pluGET#31]
## Describe the bug
The "`check all`" command paired with a modified "[SFTP] `pathtoseperatedownloadpath`" config option causes pluGET to (judging by the traceback) attempt to access a path which doesn't exist (which would have been created during a plugin "update").

An example of this non-existent path is:
/plugins/pluGET/Essentials

## To Reproduce
Steps to reproduce the behaviour:
1. Edit config.ini
1a. [SFTP] `separatedownloadpath = True`
1b. [SFTP] `pathtoseperatedownloadpath = /plugins/pluGET`
2. Run `./launcher.sh`
3. Enter the command "`check all`"

## Expected behavior
"[SFTP] `separatedownloadpath`" should be ignored/assumed as `False`, as you are "checking" for updates. No new plugin updates are being downloaded (as they would be with the `update` command).

The command should behave identically to as if "[SFTP] `separatedownloadpath`" were set to `False`.

## Desktop
 - OS: Linux (RedHat family)

## Additional context
I have made sure that the `/plugins/pluGET` path does already exist, and the same error persists.

When setting "[SFTP] `separatedownloadpath = False`" and following all of the other reproduction steps, the command "`check all`" works flawlessly.

**Other config options I have set which may be relevant:**

- [General] `uselocalpluginfolder = False`
- [SFTP] `use_sftp = True`

**Full traceback:**
```
Exception has occurred: FileNotFoundError
[Errno 2] No Such File
  File "~/pluGET/src/handlers/handle_sftp.py", line 97, in sftp_validateFileAttributes
    pluginSFTPAttribute = sftp.lstat(pluginPath)
  File "~/pluGET/src/plugin/plugin_updatechecker.py", line 164, in checkInstalledPackage
    pluginAttributes = sftp_validateFileAttributes(connection, pluginFile)
  File "~/pluGET/src/handlers/handle_input.py", line 64, in handleInput
    checkInstalledPackage(inputSelectedObject, inputParams)
  File "~/pluGET/src/handlers/handle_input.py", line 105, in getInput
    handleInput(inputCommand, inputSelectedObject, inputParams)
  File "~/pluGET/src/__main__.py", line 14, in mainFunction
    getInput()
  File "~/pluGET/src/__main__.py", line 16, in <module>
    mainFunction()
```

**Comment by Neocky** [comment]
### Hey @smcclennon,

thank you for your in-depth bug report!
I just released a new version which fixes your issue. Download it here: [v1.6.3](https://github.com/Neocky/pluGET/releases/tag/v1.6.3)

The problem was that it checked if the old plugin files are valid in the seperate download path folder and not in the initial plugins folder. That was the reason the plugins couldn't be found and the error got printed.

#### Just update to the new version and you are good to go! 😃 

### Thank you for flying with pluGET! 🚀
