### ISSUE TITLE
Outdated plugin not registered as requiring update

### ISSUE THREAD

**Issue by nathanielcutajar** [Neocky/pluGET#33]
**Describe the bug**
PlaceholderApi plugin was updated yesterday (as of this report) and it is showing as not requiring an update even though locally I have `2.10.9` and there is version `2.10.10` available (as of this bug report). Might affect other plugins

**To Reproduce**
1) Download version 2.10.9
2) Run script (check all)

**Expected behavior**
The color will show as green and adds it to the items to update

**Screenshots**
![image](https://user-images.githubusercontent.com/9025825/125618759-559b0c2f-705c-4e84-8bfe-1a302e93f712.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04 (5.4.0-77-generic)

**Additional context**
N/A

**Comment by Neocky** [comment]
#### Hey @nathanielcutajar,
i just released an update which fixes this issue!
Download the new version and you are good to go: [v1.6.5](https://github.com/Neocky/pluGET/releases/tag/v1.6.5)

### Thank you for flying with pluGET 🚀
