### ISSUE TITLE
Crash on buggy version check

### ISSUE THREAD

**Issue by nathanielcutajar** [Neocky/pluGET#35]
**Describe the bug**
Tried to do a check for updates for some plugins on my bungeecord server, and it just crashed

**To Reproduce**
1) Have the plugins I have installed
2) Run `check all`

**Expected behavior**
The app should either manage to check, or at least if there is a file that does not have a plugin.yml, should skip it rather than crash the application

**Screenshots**
![image](https://user-images.githubusercontent.com/9025825/125635724-346249e3-429a-4c4f-84de-f8b705357a69.png)

![image](https://user-images.githubusercontent.com/9025825/125635674-e59186ea-14fc-4b73-b055-cdc6b035680f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (5.4.0-77-generic)

**Additional context**
I am aware that this app is not designed to work on BungeCoord but this is more of a matter of validation rather than compatibility. App should not crash like this when something is wrong with one of the jar files.

**Comment by Neocky** [comment]
Hey @nathanielcutajar,
i just released an update which fixes this issue.
Download the new version and you are good to go: v1.6.5

Thank you for flying with pluGET 🚀
