### ISSUE TITLE
ftp object has no attribute lstat

### ISSUE THREAD

**Issue by leSs-cOws** [Neocky/pluGET#37]
![Screenshot_36](https://user-images.githubusercontent.com/16761291/126741484-f7df6715-4a73-4492-bfed-431b571c19eb.png)
I believe this may have something to do with the fact that there is an @ sign in my ftp username but i cant be sure. Thought i would add it here in case its a bug.

**Comment by Neocky** [comment]
### Hey @leSs-cOws,
unfortunately i am currently very busy but i can take a look if i have some free time. 
Can you send me a list of your plugins?
Thanks a lot!

**Comment by leSs-cOws** [comment]
Sure, these are my plugin list. AdvancedBan, BanItem, ChatManager, CMILib, ConsoleSpamFix, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), GriefPrevention, HomeSpawn, InventoryRollbackPlus, Jobs, LuckPerms, Multiverse-Core, OpenInv, PlaceholderAPI, PlayerKits, ProtocolLib, PvPToggle, RankGrantPlus, ServerListMotdSpigot, ServerRestart, SuperVanish, TAB, TwitchSync*, Vault, ViaBackwards, ViaVersion, WorldGuard

Idk if its an issue with python because it says that ftp does not have lstat. I am using ftp instead of sftp because sftp does not work with my host.

**Comment by Neocky** [comment]
### Hey @leSs-cOws,

thank you for your patience! 😀
I just released an update which fixes your problem.
Download it and you are good to go: [v1.6.7](https://github.com/Neocky/pluGET/releases/tag/v1.6.7)

### Thank you for flying with pluGET 🚀

**Comment by leSs-cOws** [comment]
Great thank you!
