### ISSUE TITLE
pluGET Downgrades Skript

### ISSUE THREAD

**Issue by Games-Crack** [Neocky/pluGET#42]
**Describe the bug**
I have a newer version of a plugin (called Skript), but pluGET wants to downgrade it

**To Reproduce**
1. Download the newest Version of Skript from GitHub
2. install it in the plugin folder
3. Check for upgrade
4. Upgrade Plugins
5. Check Again for version
4. See error.

**Expected behavior**
pluGET should not downgrade if a newer version is available. (check if local version is newer than in Plugin repo)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, 21H1

**Comment by Neocky** [comment]
### Hey @Games-Crack,

this was fixed in version [v1.7.0](https://github.com/Neocky/pluGET/releases/tag/v.1.7.0) with my tests.

### Have a good day :wave:
