### ISSUE TITLE
Add Purpur, Airplane and Tuinity Server Jars

### ISSUE THREAD

**Issue by TheTwoBoom** [Neocky/pluGET#43]

**Comment by RehanPlayz** [comment]
+1

**Comment by Neocky** [comment]
Added Waterfall & Velocity in Version [v1.7.0](https://github.com/Neocky/pluGET/releases/tag/v.1.7.0)

**Comment by Neocky** [comment]
Feel free to do that! This would be great 😃

**Comment by Neocky** [comment]
### Hey @TheTwoBoom,
i added Purpur support in the latest version [v.1.7.1](https://github.com/Neocky/pluGET/releases/tag/v1.7.1)
