### ISSUE TITLE
Pterodactyl support?

### ISSUE THREAD

**Issue by AGuyNamedJens** [Neocky/pluGET#48]
**Is your feature request related to a problem? Please describe.**
Is this supporting pterodactyl? As in, can I auto-update plugins inside of pterodactyl servers?

**Describe the solution you'd like**
Looking at how this is CLI-based. I would love to have a guide, or a way to use this on pterodactyl, they're basically docker containers (accessible on the host machine, or with SFTP though). So customer's plugins auto-update?

**Describe alternatives you've considered**
I have tried running this on the host machine, seems like i haven't found a way yet to do this for pterodactyl.

**Additional context**
If needed, please reply with anything i need to provide.

**Comment by AGuyNamedJens** [comment]
Hey @Neocky, I know there's a way to manually get into pterodactyl containers on the VPS, but yeah. No idea if you could actually manually specify it. This would also make it impossible for users of my panel to use it though..

something that might work is to add a custom feature to my panel which includes running pluGET? Maybe any possibility if u can look into this?

**Comment by Neocky** [comment]
Hey @AGuyNamedJens,

i am sorry but i don't currently have the capacity to look into a custom features for the panel.
I will close this issue now
