### ISSUE TITLE
New logo proposal

### ISSUE THREAD

**Issue by treier57lol** [Neocky/pluGET#52]
I think the logo for this project could have a bit more character, so I quickly made a design with four versions based on the current one. The base design has a plug added to symbolize the projects core feature, package management for plugins. _It's in the name, so it does seem pretty important._ Additional variants have either an arrow on the side or a visible seam on the top or both.
\
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/33978534/177057416-d3295524-3ac7-4341-a37e-0658ce3a97cc.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/33978534/177061989-b795c903-5f07-4540-84dd-f9bb7bf52e98.png">
  <img alt="Mock-up 1" src="https://user-images.githubusercontent.com/33978534/177061989-b795c903-5f07-4540-84dd-f9bb7bf52e98.png">
</picture>
\
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/33978534/177057417-59e0cc5d-8724-4494-91d2-36a1303699a8.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/33978534/177061990-931ece79-fad5-482a-8111-e1c3ac70660e.png">
  <img alt="Mock-up 2" src="https://user-images.githubusercontent.com/33978534/177061990-931ece79-fad5-482a-8111-e1c3ac70660e.png">
</picture>
\
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/33978534/177057795-3e2cee2c-6143-437b-9603-1ddbc32056ec.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/33978534/177061991-8c681250-e2a9-4b28-9189-ebc233c0c99a.png">
  <img alt="Mock-up 3" src="https://user-images.githubusercontent.com/33978534/177061991-8c681250-e2a9-4b28-9189-ebc233c0c99a.png">
</picture>
\
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/33978534/177057797-cbfa3c88-4c53-4e6b-88bb-8ecb34fadadd.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/33978534/177061992-77bfd731-77a4-4ff4-b0bf-016993b4bcab.png">
  <img alt="Mock-up 4" src="https://user-images.githubusercontent.com/33978534/177061992-77bfd731-77a4-4ff4-b0bf-016993b4bcab.png">
</picture>

These designs were made in Inkscape and the font used is Comfortaa by Johan Aakerlund, which is licensed under the Open Font License. All designs are subject to change. I haven't adjusted kerning and some other tweaks could be done like more rounded corners akin to the original. Maybe there could be something added to symbolize Minecraft more. 
The plug graphic may also need to be made bigger to have a more usable small icon (judge for yourself: <picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/33978534/177062132-78d3bcc2-3781-47b5-8e0e-ccc8521c2ac1.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/33978534/177062169-dea8f1ad-8ef7-41e6-b060-7fb656eb6938.png">
  <img alt="Icon" src="https://user-images.githubusercontent.com/33978534/177062169-dea8f1ad-8ef7-41e6-b060-7fb656eb6938.png">
</picture>).

This is of course just a proposal and I understand if this seems unnecessary. Regardless, I had fun making these. However, if this does seem like something worth pursuing then I can finalize the design(s) and supply the vector files.
##### Sidenote: You can change which image is displayed depending on the chosen GitHub theme which I have used here to show either full white or black versions of the designs.

**Comment by Neocky** [comment]
### Hey @treier57lol,
wow i never knew that you can choose the preferred image depending on the GitHub theme. 
All in all these logos do have more character than the actual logo which I designed quickly and since then never touched. 😆 
I also like the idea of the added plug which is a nice detail. I would also like if the logo could have something which symbolize Minecraft more. Do you have an idea for that?

**Comment by treier57lol** [comment]
> I would also like if the logo could have something which symbolize Minecraft more. Do you have an idea for that?

Maybe one side of the box could have a Creeper face? I'll quickly make a version like this.

**Comment by treier57lol** [comment]
How's this?

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/33978534/177181902-d5cb867b-e9d9-45bb-9555-50aa70f9d0c8.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/33978534/177181897-2b8addd0-b024-4853-9b94-6a9bf15a8987.png">
  <img alt="Mock-up 5" src="https://user-images.githubusercontent.com/33978534/177181897-2b8addd0-b024-4853-9b94-6a9bf15a8987.png">
</picture>

**Comment by treier57lol** [comment]
>Can you also show me a version without the down arrow?

Can do! Two versions with the Creeper face facing either side.

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/33978534/179701845-0f885b77-9c68-400f-98e7-d7510629c275.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/33978534/179701843-a57b9a59-1984-4d2c-a223-06b0ee83b7e7.png">
  <img alt="Mock-up 6" src="https://user-images.githubusercontent.com/33978534/179701843-a57b9a59-1984-4d2c-a223-06b0ee83b7e7.png">
</picture>

\
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/33978534/179701848-7592f10b-06f3-41fe-b206-db8683d0fda3.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/33978534/179701847-eb32006d-fe26-4185-9e05-7cf292bfa501.png">
  <img alt="Mock-up 7" src="https://user-images.githubusercontent.com/33978534/179701847-eb32006d-fe26-4185-9e05-7cf292bfa501.png">
</picture>

**Comment by Neocky** [comment]
I like the first one. If you want you can send me the vector files and I can add it to the project as new logo.

**Comment by treier57lol** [comment]
I will do some quick touch-ups and create a merge request.
