### ISSUE TITLE
First Time Run - No module named 'ruamel'

### ISSUE THREAD

**Issue by Circenn5130** [Neocky/pluGET#62]
**Describe the bug**
pluGET-v1.7.2 
From Windows CLI when performing first time run to generate config yaml, it throws an error "**No module named 'ruamel**'"

> Traceback (most recent call last):
>   File "C:\Minecraft\Sandbox\pluGET-v1.7.2\pluget.py", line 10, in <module>
>     from src.handlers.handle_config import check_config, validate_config
>   File "C:\Minecraft\Sandbox\pluGET-v1.7.2\src\handlers\handle_config.py", line 7, in <module>
>     import ruamel.yaml
> ModuleNotFoundError: No module named 'ruamel'
> 

**To Reproduce**

- Install Windows python 3.10.4 x64
- Run **install_requirements_WINDOWS.bat**
- (Using Windows CLI) run **py pluget.py**

**Expected behavior**
Generation of pluGET_config.yaml

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Circenn5130** [comment]
Re-running install_requirements_WINDOWS.bat resolved issue and I was able to successfully generate config

**Comment by Jackalack7234** [comment]
I’m having this issue, and no matter how many times I run the install requirements batch file, it still gives this error
