### ISSUE TITLE
Error - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by siroo2137** [Neocky/pluGET#63]
**Describe the bug**

Traceback (most recent call last):
  File "pluget.py", line 12, in <module>
    from src.utils.utilities import check_requirements, api_test_spiget, check_for_pluGET_update
  File "/home/ubuntu/pluget/src/utils/utilities.py", line 35
    match command:
          ^
SyntaxError: invalid syntax

**To Reproduce**
1.install newest pluget from releases
2.install newest python3
3.run install_requirements_linux.sh
4.run pluget.py
5. See error

**Expected behavior**
Program should open, and work normally

**Desktop (please complete the following information):**
 - OS: ubuntu server 20.04 (x64)

**Comment by Neocky** [comment]
### Hey @siroo2137,
check that you have at least python 3.10.4 installed as noted in [Installation](https://github.com/Neocky/pluGET#1-python-3104)

The traceback just says that python can't recognize the `match` keyword which was introduced in the new python version.

**Comment by siroo2137** [comment]
oh, thanks
