### ISSUE TITLE
Doesn't work on RHEL 9

### ISSUE THREAD

**Issue by mrtajniak** [Neocky/pluGET#64]
I cannot use this script because it needs python 3.10 but I can only have Python 3.9. I have tried compiling Python 3.10 from source and command `python3.10` work but `pip3.10` doesn't at this point I don't know what to do

**Comment by JeremyStarTM** [comment]
Are there any python repositories available for RHEL that provide the latest packages? If yes, add them any try again.

**Comment by Neocky** [comment]
### Hey @mrtajniak,
i am sorry but I can't help you with your problem. ☹️ 
In the worst case you can try to use a different distribution in which you can install Python 3.10.4
